### ISSUE TITLE
Master branch is far behind release branches sumo and thud

### ISSUE THREAD

**Issue by KurtSchluss** [koenkooi/meta-kodi#11]
Hi, I would like to use your repository with some newer Yocto releases (master+warrior).
Unfortunately the master branch is far behind the latest release branches (sumo+thud).

Please fast-forward the master branch (and thud) to rev 84cd03 (sumo).

**Comment by koenkooi** [comment]
Done.

**Comment by KurtSchluss** [comment]
Wow. That was lightning-fast - thanks a lot!

**Comment by andrea-adami** [comment]
Hi, master needs a new bump.
TIA
