### ISSUE TITLE
thud: libffi_3.2.1 bbappend compatibility with zeus 

### ISSUE THREAD

**Issue by manju6691** [koenkooi/meta-kodi#13]
Zeus provides new version libffi_3.3~rc0 and install of ffi.h is taken care. libffi_3.2.1.bbappend should be masked to compile with Zeus.

**Comment by koenkooi** [comment]
I've made the layer not error out on dangling bbappends, so that should fix the issue on zeus.

**Comment by koenkooi** [comment]
20f236ae230b6e6bcd1d8f81b7ab27f2d46bdb4e
