### ISSUE TITLE
meta-raspberrypi/meta-meson with meta-kodi threw this error:Problem encountered: VDPAU state tracker requires at least one of the following gallium drivers: r300, r600, radeonsi, nouveau.

### ISSUE THREAD

**Issue by EzEmbedded** [koenkooi/meta-kodi#52]
branch:`hardknott`
bsp meta:`meta-raspberrypi/meta-meson`
**conf:**
```
PACKAGECONFIG_append_pn-chromium = " component-build proprietary-codecs use-vaapi"
PACKAGECONFIG_append_pn-gstreamer1.0-plugins-good = "vpx wavpack libv4l2"
LICENSE_FLAGS_WHITELIST += " commercial commercial_mpg123 commercial_libav commercial_x264 commercial_ffmpeg"
DISTRO_FEATURES_append = " virtualization systemd pam opengl egl"
IMAGE_INSTALL_append += " kodi"
DISTRO_FEATURES_remove = " x11"
```
**then run:**
`bitbake kodi`

the error is:
`mesa-21.0.3/meson.build:546:4:ERROR: Problem encountered: VDPAU state tracker requires at least one of the following gallium drivers: r300, r600, radeonsi, nouveau.`

**Comment by MarkusVolk** [comment]
https://github.com/koenkooi/meta-kodi/blob/hardknott/classes/vpu.bbclass

This happens inside vpu.bbclass. I guess we have too much automation here. Perhaps it would make sense to just remove the entire class?
For a workaround it should be sufficient to remove vpu from kodi.inc
https://github.com/koenkooi/meta-kodi/blob/ac5e11304a0bfd3fa2ba87d6dccdd4ce168256f6/recipes-multimedia/kodi/kodi.inc#L4

**Comment by superna9999** [comment]
or restrict vdpau / vaapi to x86 only

**Comment by MarkusVolk** [comment]
That falls short in my opinion. There could be cases where people would want to enable vdpau/vaapi even if not on x86. For example  the threadstarter wants to build in vaapi support for raspberrypi.

**Comment by MarkusVolk** [comment]
In general i think it would be really nice, if the list of DISTRO_FEATURES would be expanded by some entries, e.g. pipewire,vulkan,egl,gles,vaapi,vdpau ....  That would make it a lot easier to finetune builds from within recipes.

**Comment by dev-0x7C6** [comment]
@MarkusVolk 
> This happens inside vpu.bbclass. I guess we have too much automation here. Perhaps it would make sense to just remove the entire class?

Yes, probably this is too much. I think that `DISTRO_FEATURES` is good place.

I would like to share some perspective that I have:

I think we're missing something like `GPU_FEATURES`/`VIDEO_FEATURES`/`VIDEO_CARDS` or some thing similar that can drive and help pre-configuration for mesa and other recipes from supported gpu perspective. With those as standard variables every machine SoC can easily opt-in for proper gpu driver configuration and features. 

For now mesa recipe do not work as driver selector from `DISTRO_FEATURES` and we're forced to reconfigure mesa defaults which is not pretty (opinion). 

This might be seen as my another attempt to automate something, but in the end I think we will get standardized list of gpu names (which might be just 1:1 driver name from mesa)  / features which other recipes can use to properly react or reconfigure (by providing overrides) rather that force appending or judging by architecture. 

I really like what Gentoo created as fundamental variable to drive gpu configuration across system https://wiki.gentoo.org/wiki//etc/portage/make.conf#VIDEO_CARDS. Documentation here is somewhat lacking but with emerge it's really easy check what options are available and which part of system will react to it (mesa as example):

![emerge](https://devwork.space/wp-content/uploads/2021/12/example_emerge_mesa.png)
legend:
red - option is on
blue - option is off
() - means this is somewhat not available for your architecture or disabled to change

**Comment by EzEmbedded** [comment]
I tested just now in **meta-freescale**(git://git.yoctoproject.org/meta-freescale -b hardknott) and **meta-rockchip**(https://github.com/rockchip-linux/meta-rockchip.git -b yocto-next ),it seemed had passed kodi config,but stoped at
 ```
ERROR: Task (/home/yocto-crops/poky/meta/recipes-multimedia/ffmpeg/ffmpeg_4.3.2.bb:do_configure) failed with exit code '1'

DEBUG: Executing shell function do_configure
libvidstab is gpl and --enable-gpl is not specified.

```

**Comment by MarkusVolk** [comment]
Thats not a kodi issue anymore. You would need a line like this in your ffmpeg.bb or ffmpeg.bbappend:

EXTRA_OECONF += "--enable-gpl"

**Comment by MarkusVolk** [comment]
@dev-0x7C6
That looks well organised. I have been using gentoo last time about 20 years ago. Probably it improved by far  since then.
For some of these values we already have PACKAGECONFIG entries in mesa.bb. Instead of using vpu.bbclass we could also add something like this in a mesa.bbappend:

```
PACKAGECONFIG :append = " \
	${@bb.utils.filter('DISTRO_FEATURES', 'vdpau', d)} \
	${@bb.utils.filter('DISTRO_FEATURES', 'va', d)} \
	...
"
```

and add identical entries to  kodi.bb

**Comment by MarkusVolk** [comment]
Thought about doing it something like this
```

From 891c58538fa4d435f9cad6bfc920617f5a3e1522 Mon Sep 17 00:00:00 2001
From: MarkusVolk <f_l_k@t-online.de>
Date: Fri, 10 Dec 2021 07:14:03 +0100
Subject: [PATCH] va/vdpau test

Signed-off-by: MarkusVolk <f_l_k@t-online.de>
---
 classes/vpu.bbclass                         |  2 --
 recipes-graphics/mesa/mesa_%.bbappend       |  7 +++----
 recipes-multimedia/ffmpeg/ffmpeg_%.bbappend | 12 ++++++------
 recipes-multimedia/kodi/kodi.inc            |  2 +-
 recipes-multimedia/kodi/kodi_git.bb         |  6 ++----
 5 files changed, 12 insertions(+), 17 deletions(-)
 delete mode 100644 classes/vpu.bbclass

diff --git a/classes/vpu.bbclass b/classes/vpu.bbclass
deleted file mode 100644
index 2bb775c..0000000
--- a/classes/vpu.bbclass
+++ /dev/null
@@ -1,2 +0,0 @@
-VAAPISUPPORT ?= "${@bb.utils.contains('DISTRO_FEATURES', 'opengl', '1', '0', d)}"
-VDPAUSUPPORT ?= "${@bb.utils.contains('DISTRO_FEATURES', 'x11', '1', '0', d)}"
diff --git a/recipes-graphics/mesa/mesa_%.bbappend b/recipes-graphics/mesa/mesa_%.bbappend
index 7a1ae19..17d1f54 100644
--- a/recipes-graphics/mesa/mesa_%.bbappend
+++ b/recipes-graphics/mesa/mesa_%.bbappend
@@ -1,6 +1,5 @@
-inherit vpu
-
 PACKAGECONFIG:append:class-target = " \
-    ${@bb.utils.contains('VAAPISUPPORT', '1', 'va', '', d)} \
-    ${@bb.utils.contains('VDPAUSUPPORT', '1', 'vdpau', '', d)} \
+    ${@bb.utils.filter('DISTRO_FEATURES', 'vdpau', d)} \
+    ${@bb.utils.filter('DISTRO_FEATURES', 'va', d)} \
 "
+
diff --git a/recipes-multimedia/ffmpeg/ffmpeg_%.bbappend b/recipes-multimedia/ffmpeg/ffmpeg_%.bbappend
index 7705960..cd076ec 100644
--- a/recipes-multimedia/ffmpeg/ffmpeg_%.bbappend
+++ b/recipes-multimedia/ffmpeg/ffmpeg_%.bbappend
@@ -1,13 +1,13 @@
-inherit vpu
-
-PACKAGECONFIG[vidstab] = "--enable-libvidstab,--disable-libvidstab,vid.stab"
+PACKAGECONFIG[vidstab] = "--enable-libvidstab --enable-gpl,--disable-libvidstab,vid.stab"
 PACKAGECONFIG[x265] = "--enable-libx265,--disable-libx265,x265"
 
 KODIFFMPEGADDITIONALS ?= " \
-    ${@bb.utils.contains('VAAPISUPPORT', '1', 'vaapi', '', d)} \
-    ${@bb.utils.contains('VDPAUSUPPORT', '1', 'vdpau', '', d)} \
     vidstab \
     x265 \
 "
 
-PACKAGECONFIG:append = " ${KODIFFMPEGADDITIONALS}"
+PACKAGECONFIG:append = " \
+    ${@bb.utils.filter('DISTRO_FEATURES', 'va vdpau', d)} \
+    ${KODIFFMPEGADDITIONALS} \
+"
+
diff --git a/recipes-multimedia/kodi/kodi.inc b/recipes-multimedia/kodi/kodi.inc
index c29bb9e..720ca5b 100644
--- a/recipes-multimedia/kodi/kodi.inc
+++ b/recipes-multimedia/kodi/kodi.inc
@@ -1,7 +1,7 @@
 # Some forked meta-kodi repositories using custom kodi urls, personally I think they should use variable instead of
 # creating different recipes and diverse from upstream
 
-inherit kodi-common vpu
+inherit kodi-common
 
 KODIVER ?= "20.0"
 
diff --git a/recipes-multimedia/kodi/kodi_git.bb b/recipes-multimedia/kodi/kodi_git.bb
index 039ef5d..f724990 100644
--- a/recipes-multimedia/kodi/kodi_git.bb
+++ b/recipes-multimedia/kodi/kodi_git.bb
@@ -89,9 +89,7 @@ KODIVAAPIDEPENDS:append:x86 = " intel-vaapi-driver"
 KODIVAAPIDEPENDS:append:x86-64 = " intel-vaapi-driver"
 
 PACKAGECONFIG ?= " \
-  ${@bb.utils.contains('VAAPISUPPORT', '1', 'vaapi', '', d)} \
-  ${@bb.utils.contains('VDPAUSUPPORT', '1', 'vdpau', '', d)} \
-  ${@bb.utils.filter('DISTRO_FEATURES', 'bluetooth lirc pulseaudio samba systemd', d)} \
+  ${@bb.utils.filter('DISTRO_FEATURES', 'bluetooth lirc pulseaudio samba systemd va vdpau', d)} \
   ${@bb.utils.filter('KODIGRAPHICALBACKEND', 'gbm wayland x11', d)} \
   airtunes \
   joystick \
@@ -117,7 +115,7 @@ PACKAGECONFIG[optical] = "-DENABLE_OPTICAL=ON,-DENABLE_OPTICAL=OFF"
 PACKAGECONFIG[pulseaudio] = "-DENABLE_PULSEAUDIO=ON,-DENABLE_PULSEAUDIO=OFF,pulseaudio"
 PACKAGECONFIG[samba] = ",,samba"
 PACKAGECONFIG[systemd] = ",,,kodi-systemd-service"
-PACKAGECONFIG[vaapi] = "-DENABLE_VAAPI=ON,-DENABLE_VAAPI=OFF,${KODIVAAPIDEPENDS},${KODIVAAPIDEPENDS}"
+PACKAGECONFIG[va] = "-DENABLE_VAAPI=ON,-DENABLE_VAAPI=OFF,${KODIVAAPIDEPENDS},${KODIVAAPIDEPENDS}"
 PACKAGECONFIG[vdpau] = "-DENABLE_VDPAU=ON,-DENABLE_VDPAU=OFF,libvdpau,mesa-vdpau-drivers"
 
 # Compilation tunes
-- 
2.25.1
```

but i'm fine with the current state also

**Comment by dev-0x7C6** [comment]
> ${@bb.utils.filter('DISTRO_FEATURES', 'vdpau', d)}
> ${@bb.utils.filter('DISTRO_FEATURES', 'va', d)}

I think there is a chance to propose those selectors into meta-oe. Let's remove vpu.bbclass for now and stay with appends.

**Comment by EzEmbedded** [comment]
I tested meta-kodi branch master-next,but have the fellow error,I'm using docker crops/poky:
```
do_configure: ExecutionError('/home/yocto-crops/build/tmp/work/aarch64-poky-linux/fstrcmp/0.7-r0/temp/run.do_configure.33063', 1, None, None)
Currently 15 running tasks (3960 of 5354)  73% |###################################################                   |ERROR: Logfile of failure stored in: /home/yocto-crops/build/tmp/work/aarch64-poky-linux/fstrcmp/0.7-r0/temp/log.do_configure.33063
Log data follows:
| DEBUG: Executing shell function autotools_preconfigure
....
| checking for libtool... no
| 
|         You must have GNU Libtool installed to build fstrcmp.
|         Homepage: http://www.gnu.org/software/libtool/
| 
|         If you are using a package based install, you will need the
|         libtool package.
| 
| NOTE: The following config.log files may provide further information.
| NOTE: /home/yocto-crops/build/tmp/work/aarch64-poky-linux/fstrcmp/0.7-r0/fstrcmp-0.7.D001/config.log
| ERROR: configure failed
```

**Comment by MarkusVolk** [comment]
https://github.com/koenkooi/meta-kodi/commit/da541ee07b6f4320683a18d8a209b30bf58f2090

if you dont use recent poky master branch you need to undo this commit

Please create new issues for new issues ;)
